project:
  type: website
  output-dir: docs
website:
  repo-url: https://github.com/lsmacoris
  repo-actions: [edit, issue]
  title: "Lucas S. Macoris"
  site-url: 'https://lsmacoris.github.io'
  site-path: '/'
  google-analytics: "G-87FLN5SXEJ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: https://lsmacoris.github.io/lectures
        text: Lecture Notes
      - href: academic.qmd
        text: Academic Research
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/lsmacoris
        aria-label: GitHub
      - icon: envelope
        href: mailto:lucasmacoris@gmail.com
        aria-label: Email
      - icon: linkedin
        href: https://www.linkedin.com/in/lucas-macoris-390a47160/
        aria-label: LinkedIn
      - icon: file-pdf
        href: https://drive.google.com/file/d/184m-BDeB-31SSyEuzqINco2UzqRFXhma/view?usp=drive_link
        aria-label: CV
      
  page-footer: 
   background: dark
   left: Copyright 2025, Lucas Macoris. Photography by [Juliana Rizieri](https://www.jurizieri.com.br/).
   right: Built with [Quarto](https://quarto.org/)

format:
  html:
    page-layout: full
    theme:
      light: [flatly,light.scss]
      dark: [darkly,dark.scss]

from: markdown+emoji


