---
  title: "**What I have been reading recently...**"
---
---
In case you wonder what are good reading tips, here's a few list of very interesting, technical papers that I have been reading extensively and I recommend to everyone that is interested in applied economics (and, in some cases, quantitative marketing):

## **Marketing Mix Modeling**

1. [Challenges and Opportunities in Media Mix Modeling](https://static.googleusercontent.com/media/research.google.com/pt-BR//pubs/archive/45998.pdf)

2. [Bayesian Methods for Media Mix Modeling with Carryover and Shape Effects](https://static.googleusercontent.com/media/research.google.com/pt-BR//pubs/archive/46001.pdf)


3. [A Comparison of Approaches to Advertising Measurement: Evidence from Big Field Experiments at Facebook](https://www.kellogg.northwestern.edu/faculty/gordon_b/files/fb_comparison.pdf)

## **Methods in Applied (Micro)economics**

1. [What's trending in difference-in-differences? A synthesis of the recent econometrics literature](https://www.sciencedirect.com/science/article/abs/pii/S0304407623001318)

2. [Difference-in-Differences with multiple time periods](https://www.sciencedirect.com/science/article/abs/pii/S0304407620303948?via%3Dihub)

3. [Mostly Harmless Econometrics: an Empiricist's Companion](https://www.mostlyharmlesseconometrics.com/) this has been a good companion since always.
