---
  title: "**Lecture Notes and Handouts**"
  engine: knitr
---
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

::: {.justify}

Within this section, you'll discover a meticulously organized repository containing my lecture notes from FGV-EAESP, technical handouts, and illustrative code samples. Most, if not all, of these resources extensively leverage [Quarto](www.quarto.org), an open-source scientific and technical publishing system that supports *R*, *Python*, *Julia*, and *Observable*. Quarto offers a seamless and scalable solution for sharing technical content, encompassing a blend of plain text and executable code, being applicable to static document formats like .pdf files and dynamic, interactive presentations facilitated by [Reveal JS](https://revealjs.com/).

For comprehensive guidance on harnessing Quarto for presentations and technical content in a standardized and comprehensive manner, please refer to the official [reference](https://quarto.org/docs/reference/) material.
 
## **Financial Management (work-in-progress)**

These series of slides and lecture notes relate to the *Financial Management* course (undergraduate level, FGV-EAESP). **Content TBD**.


:::
